// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjCXgM73h3xcU2lp12GESuuB5UXsS-lak',
    appId: '1:226709067191:web:55c00b17468125a4fb4432',
    messagingSenderId: '226709067191',
    projectId: 'psm2-8c2fc',
    authDomain: 'psm2-8c2fc.firebaseapp.com',
    storageBucket: 'psm2-8c2fc.firebasestorage.app',
    measurementId: 'G-T56Y1KZ63D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOb4BUhws831tM1TNaiA7ZB8xa-O0YGu0',
    appId: '1:226709067191:android:747d253ef4874b82fb4432',
    messagingSenderId: '226709067191',
    projectId: 'psm2-8c2fc',
    storageBucket: 'psm2-8c2fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZb6b_TYwYkOuA8HswTOChJHGmh_8_R9k',
    appId: '1:226709067191:ios:883c20fdeca34de5fb4432',
    messagingSenderId: '226709067191',
    projectId: 'psm2-8c2fc',
    storageBucket: 'psm2-8c2fc.firebasestorage.app',
    iosBundleId: 'com.example.psm',
  );
}
